### ISSUE TITLE
Alternative for drop downs

### ISSUE THREAD

**Issue by rangarajanps** [bimsina/fluttertemplates.dev#2]
Hi,

I am looking for alternatives for drop down as flutter ready made widgets. Refer https://medium.com/@kollinz/dropdown-alternatives-for-better-mobile-forms-53e40d641b53 for list of widgets to build.

Thanks,
Ranga

**Comment by bimsina** [comment]
Simple, styled, and autocomplete dropdowns have been added here: https://fluttertemplates.dev/widgets/must_haves/dropdowns
