### ISSUE TITLE
I want to contribute to the fluttertemplates.dev!

### ISSUE THREAD

**Issue by AdityaMotale** [bimsina/fluttertemplates.dev#3]
## Want to contribute
I'm inspired by your awesome project and want to start open source. 

## About
Hello! My name is Adii. I'm a intermediate flutter dev. 
I'm really inspired by your project and want to contribute by adding some widget snippets
Can you guide me how can I? 
Thank you for this awesome project and I wish you'll have a good day ahead

**Comment by bimsina** [comment]
You can start by adding proposals for widgets that you would like to be added [here](https://github.com/bimsina/fluttertemplates.dev/issues/new?assignees=&labels=widget_template&template=request-a-new-widget.md).

I am also working on adding documentation for the project and contributing docs.
